# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
