# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(default='teste', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider_name',
            field=models.CharField(default='teste', max_length=250),
            preserve_default=False,
        ),
    ]
